import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState, useEffect } from "react";
import { Dog } from "./utils/types/types";
import AddDogForm from "@/components/AddDogForm";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [dogs, setDogs] = useState<Dog[]>([]);
  useEffect(() => {
    fetch("/api/dogs")
      .then((res) => res.json())
      .then((dogs) => setDogs(dogs as Dog[]));
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <AddDogForm setDogs={setDogs} />
        {dogs.length > 0 &&
          dogs.map((dog, index) => (
            <li key={index}>
              <h2>{dog.name}</h2>
              <p>{dog.nicknames[0]}</p>
              <p>{dog.isFluffy ? "True" : "Rough"}</p>
              <p>{dog.age}</p>
              <p>{dog.size}</p>
            </li>
          ))}
      </main>
    </>
  );
}
